### ISSUE TITLE
Temprature setpoint

### ISSUE THREAD

**Issue by tamager144** [quantenschaum/egg-incubator#5]
Hi, I seem to not be able to set the temperature and humidity setpoint, when I press the keys they don't seem to do anything.
I am new to coding and understand something but this got a bit to hard for me.

**Comment by lefterisgar** [comment]
The way I solved the issue was to trigger an eeprom reset by uncommenting one line. Have a look here: https://arduino.stackexchange.com/questions/60268/nan-values-in-egg-incubator
