### ISSUE TITLE
Missing SoftwareServo.h

### ISSUE THREAD

**Issue by Mazewind-collab** [quantenschaum/egg-incubator#7]
I have a problem when I upload, it keeps saying missing software servo.h 
Screenshot: https://cdn.discordapp.com/attachments/841747860542062633/861269543649673216/unknown.png

**Comment by enriquesmw** [comment]
solved it: https://drive.google.com/file/d/0B6s_UhmkBLQfVTVQWEh6aS1yb0E/view?usp=sharing

**Comment by Mazewind-collab** [comment]
Oh ok, thanks!
